# Generated by Django 5.2.7 on 2025-10-27 05:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_posting_globally', models.BooleanField(default=True, help_text='Master switch to allow or disallow all new posts.')),
                ('min_time_between_posts', models.PositiveIntegerField(default=60, help_text='Minimum time in seconds a user must wait between posts.')),
                ('enable_blocked_words_check', models.BooleanField(default=True, help_text='Enable to check submissions against the BlockedWords list.')),
                ('enable_llm_analysis', models.BooleanField(default=True, help_text='Enable to send messages to an LLM for spam/harmful/promotion checks.')),
                ('charge_for_promotional_posts', models.BooleanField(default=False, help_text='Enable to require payment for posts flagged as promotional.')),
                ('promotional_post_fee', models.DecimalField(decimal_places=2, default=5.0, help_text='Cost for a promotional post.', max_digits=6)),
                ('charge_for_image_uploads', models.BooleanField(default=False, help_text='Enable to require payment when a user uploads their own images.')),
                ('image_upload_fee', models.DecimalField(decimal_places=2, default=2.0, help_text='Cost for uploading images with a post.', max_digits=6)),
                ('enable_paid_instant_post', models.BooleanField(default=False, help_text='Allow users to pay to bypass the posting queue if API limits are hit.')),
                ('instant_post_fee', models.DecimalField(decimal_places=2, default=1.0, help_text='Cost to post immediately when the queue is active.', max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.PositiveIntegerField(db_index=True, help_text='Unique, sequential post number starting from 2100.', unique=True, validators=[django.core.validators.MinValueValidator(2100)])),
                ('text_content', models.TextField(max_length=2200)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('SCHEDULED', 'Scheduled'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('submission_ip', models.GenericIPAddressField()),
                ('submission_user_agent', models.CharField(max_length=255)),
                ('instagram_media_id', models.CharField(blank=True, help_text='The media ID returned by the Instagram API upon successful posting.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp of when the post was successfully uploaded to Instagram.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name the user provides on their first visit.', max_length=50)),
                ('tracking_cookie', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique identifier stored in the user's browser cookie.", unique=True)),
                ('is_hard_blocked', models.BooleanField(db_index=True, default=False, help_text='If true, this user is permanently banned from posting.')),
                ('flags_count', models.PositiveIntegerField(default=0, help_text="Counter for how many times this user's posts have been flagged.")),
                ('initial_ip', models.GenericIPAddressField(blank=True, help_text='The first IP address used by this user.', null=True)),
                ('initial_user_agent', models.CharField(blank=True, help_text="The first user agent string from the user's browser.", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BLOCKED_WORD', 'Blocked Word'), ('LLM_SPAM', 'LLM: Spam'), ('LLM_HARMFUL', 'LLM: Harmful Content')], max_length=20)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Admin has reviewed this flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL to the image stored in S3.', max_length=1024)),
                ('is_text_image', models.BooleanField(default=False, help_text='True if this is the auto-generated image from text, False for user uploads.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.user'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description of the action (e.g., 'submit_post', 'payment_initiated').", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
