# Generated by Django 5.2.7 on 2025-11-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='The word to block. Checks will be case-insensitive.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_posting_globally', models.BooleanField(default=True, help_text='Master switch to allow or disallow all new posts.')),
                ('min_time_between_posts', models.PositiveIntegerField(default=30, help_text='Minimum time in seconds a user must wait between posts.')),
                ('enable_blocked_words_check', models.BooleanField(default=True, help_text='Enable to check submissions against the BlockedWords list.')),
                ('enable_llm_analysis', models.BooleanField(default=True, help_text='Enable to send messages to an LLM for spam/harmful/promotion checks.')),
                ('charge_for_promotional_posts', models.BooleanField(default=False, help_text='Enable to require payment for posts flagged as promotional.')),
                ('promotional_post_fee', models.DecimalField(decimal_places=2, default=4.99, help_text='Cost for a promotional post.', max_digits=6)),
                ('charge_for_image_uploads', models.BooleanField(default=False, help_text='Enable to require payment when a user uploads their own images.')),
                ('image_upload_fee', models.DecimalField(decimal_places=2, default=1.49, help_text='Cost for uploading images with a post.', max_digits=6)),
                ('enable_paid_instant_post', models.BooleanField(default=False, help_text='Allow users to pay to bypass the posting queue if API limits are hit.')),
                ('instant_post_fee', models.DecimalField(decimal_places=2, default=0.99, help_text='Cost to post immediately when the queue is active.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
