# Generated by Django 5.2.7 on 2025-12-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='instagram_access_token',
            field=models.CharField(blank=True, help_text="The 'Never-Expiring' Page Access Token for Instagram/Facebook API.", max_length=500, null=True),
        ),
    ]
