# Generated by Django 5.2.7 on 2025-11-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('BLOCKED_WORD', 'Blocked Word'), ('LLM_SPAM', 'LLM: Spam'), ('LLM_HARMFUL', 'LLM: Harmful Content')], help_text='The reason this post was flagged.', max_length=20)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, help_text='Set to True once an admin has approved or rejected the post.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flag', to='posts.post')),
            ],
            options={
                'verbose_name': 'Flagged Message',
                'verbose_name_plural': 'Flagged Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
