# Generated by Django 5.2.7 on 2025-11-11 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.CharField(choices=[('PROMOTIONAL_POST', 'Promotional Post'), ('IMAGE_UPLOAD', 'Image Upload Fee'), ('INSTANT_POST', 'Paid Instant Post')], default='PROMOTIONAL_POST', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in the specified currency.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
