# Generated by Django 5.2.7 on 2025-11-01 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name the user provides on their first visit.', max_length=50)),
                ('tracking_cookie', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique identifier stored in the user's browser cookie.", unique=True)),
                ('is_hard_blocked', models.BooleanField(db_index=True, default=False, help_text='If true, this user is permanently banned from posting.')),
                ('flags_count', models.PositiveIntegerField(default=0, help_text="Counter for how many times this user's posts have been flagged.")),
                ('initial_ip', models.GenericIPAddressField(blank=True, help_text='The first IP address used by this user.', null=True)),
                ('initial_user_agent', models.CharField(blank=True, help_text="The first user agent string from the user's browser.", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description of the action (e.g., 'submit_post', 'payment_initiated').", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
