# Generated by Django 5.2.7 on 2025-11-01 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.PositiveIntegerField(db_index=True, help_text='Unique, sequential post number starting from 2100.', unique=True, validators=[django.core.validators.MinValueValidator(2100)])),
                ('text_content', models.TextField(help_text="The user's message (max 2200 chars for Instagram).", max_length=2200)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PROCESSING', 'Processing'), ('SCHEDULED', 'Scheduled'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=20)),
                ('submission_ip', models.GenericIPAddressField()),
                ('submission_user_agent', models.CharField(max_length=255)),
                ('instagram_media_id', models.CharField(blank=True, help_text='The media ID returned by the Instagram API upon successful posting.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp of when the post was successfully uploaded to Instagram.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user')),
            ],
            options={
                'ordering': ['-post_number'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL to the image stored in S3.', max_length=1024)),
                ('is_text_image', models.BooleanField(default=False, help_text='True if this is the auto-generated image from text, False for user uploads.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
