# Generated by Django 5.2.7 on 2025-11-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='llm_moderation_response',
            field=models.JSONField(blank=True, help_text='The raw JSON response from the LLM moderation analysis.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.CharField(blank=True, help_text='The reason this post was flagged (e.g., Blocked Word, LLM Harmful).', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING_MODERATION', 'Pending Moderation'), ('PROCESSING', 'Processing'), ('POSTED', 'Posted'), ('FAILED', 'Failed')], db_index=True, default='PROCESSING', max_length=20),
        ),
    ]
