# Generated by Django 5.2.7 on 2025-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_llm_moderation_response_post_moderation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_promotional',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if the LLM analysis identifies the post as promotional.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the post was successfully uploaded to a social media platform.', null=True),
        ),
    ]
