# Generated by Django 5.2.7 on 2025-12-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_promotional_alter_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_api_error',
            field=models.JSONField(blank=True, help_text='Full JSON error response from Meta Graph API for debugging.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_api_status',
            field=models.PositiveIntegerField(blank=True, help_text='HTTP Status Code returned by the Meta API (e.g. 400, 500).', null=True),
        ),
    ]
